global using System;
global using System.Collections.Frozen;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Linq;
global using System.Text;
global using System.Text.RegularExpressions;
global using AdventOfCode.Utils;
global using AdventOfCode.Utils.Parser;